#pragma once

#include <spdlog/spdlog.h>

#include <nlohmann/json.hpp>
#include <optional>
#include <stdexcept>
#include <string>
#include <vector>

#include "conf.hpp"
#include "pipeline/schedule.hpp"

// ---------------------------------------------------------------------
// Helper function: Reads chunks from a JSON configuration file.
// It ignores any static/global fields and only extracts the "chunks" array
// from the "schedule" object.
// ---------------------------------------------------------------------
inline std::vector<Schedule> readSchedulesFromJson(const nlohmann::json& j) {
  std::vector<Schedule> schedules;

  // The schedule feed is machine-generated by the optimizer; a malformed feed is
  // an upstream bug, so fail fast (throw) rather than silently degrading to a
  // wrong/empty schedule that the profiler would then measure as if it were real.
  if (!j.is_array()) {
    throw std::runtime_error("Schedule JSON is not an array of solutions");
  }

  // Process each solution in the array
  for (const auto& solution : j) {
    Schedule schedule;

    // Extract UID if available
    if (solution.contains("uid")) {
      schedule.uid = solution["uid"].get<std::string>();
      spdlog::debug("Found schedule with UID: {}", schedule.uid);
    } else {
      schedule.uid = "unknown";
      spdlog::warn("Schedule missing 'uid' field, using default 'unknown'");
    }

    if (!solution.contains("chunks")) {
      throw std::runtime_error("Schedule [" + schedule.uid + "] missing 'chunks' field");
    }

    const auto& chunks_json = solution["chunks"];
    if (!chunks_json.is_array()) {
      throw std::runtime_error("Schedule [" + schedule.uid + "] 'chunks' is not an array");
    }

    // Process each chunk in the solution
    for (const auto& chunk_json : chunks_json) {
      ChunkConfig chunk;

      if (!chunk_json.contains("core_type") || !chunk_json.contains("start_stage") ||
          !chunk_json.contains("end_stage")) {
        throw std::runtime_error(
            "Schedule [" + schedule.uid +
            "] chunk missing required field 'core_type', 'start_stage', or 'end_stage'");
      }

      // Get the core type string and convert to ExecutionModel and ProcessorType
      std::string core_type = chunk_json["core_type"].get<std::string>();

      // Set execution model based on core type
      if (core_type == "GPU") {
        // Check if hardware field is present to determine the GPU type
        if (chunk_json.contains("hardware")) {
          std::string hardware = chunk_json["hardware"].get<std::string>();
          if (hardware == "gpu_cuda") {
            chunk.exec_model = ExecutionModel::kCuda;
            spdlog::debug("Using CUDA for GPU chunk based on hardware field");
          } else if (hardware == "gpu_vulkan") {
            chunk.exec_model = ExecutionModel::kVulkan;
            spdlog::debug("Using Vulkan for GPU chunk based on hardware field");
          } else {
            throw std::runtime_error("Schedule [" + schedule.uid +
                                     "] GPU chunk has unknown hardware '" + hardware +
                                     "' (expected gpu_cuda or gpu_vulkan)");
          }
        } else {
          throw std::runtime_error("Schedule [" + schedule.uid +
                                   "] GPU chunk missing 'hardware' field (gpu_cuda/gpu_vulkan)");
        }
        chunk.cpu_proc_type = std::nullopt;
      } else {
        chunk.exec_model = ExecutionModel::kOMP;

        // Map the core type string to ProcessorType
        if (core_type == "Little") {
          chunk.cpu_proc_type = ProcessorType::kLittleCore;
        } else if (core_type == "Medium") {
          chunk.cpu_proc_type = ProcessorType::kMediumCore;
        } else if (core_type == "Big") {
          chunk.cpu_proc_type = ProcessorType::kBigCore;
        } else {
          throw std::runtime_error("Schedule [" + schedule.uid + "] chunk has unknown core_type '" +
                                   core_type + "' (expected Little/Medium/Big/GPU)");
        }
      }

      // Stages are explicit and 1-based inclusive in the contract
      // (schemas/schedule.schema.json) -- read them verbatim, no array inference and
      // no +1 base-shift. validate_schedule_coverage() below enforces contiguity.
      chunk.start_stage = chunk_json["start_stage"].get<int>();
      chunk.end_stage = chunk_json["end_stage"].get<int>();
      if (chunk.start_stage < 1 || chunk.end_stage < chunk.start_stage) {
        throw std::runtime_error("Schedule [" + schedule.uid + "] chunk has invalid stage range [" +
                                 std::to_string(chunk.start_stage) + ", " +
                                 std::to_string(chunk.end_stage) + "] (need 1 <= start <= end)");
      }

      // Add the chunk to the schedule
      schedule.chunks.push_back(chunk);
    }

    // Only add schedules that have at least one valid chunk
    if (!schedule.chunks.empty()) {
      schedules.push_back(schedule);
    }
  }

  spdlog::info("Loaded {} valid schedules from JSON", schedules.size());
  return schedules;
}
